### PR TITLE
Add meta pr number 17

### PR DESCRIPTION
**Pull request by mathisto**
## If this PR were a GIF, what would it be?
Alt Text

## Description of change(s)
https://www.google.com/search?q=recursion
> Did you mean: [recursion](https://www.google.com/search?q=recursion)

View the formatted README as it will appear if this PR is merged here: https://github.com/mathisto/magicalkingdompoetsociety/tree/add-meta-pr-number-17#meta

## Diligence checklist (omit non-applicable items):
- [x] Has Readme/Wiki/documentation been updated?
- [x] Are you a lumberjack?
- [x] Is that OK?
- [x] Is this code production ready?

### CODE REVIEW

**Comment by fiteclub** [comment]
wh... eh.. but.. so..
Oh.

**Comment by dmohar** [comment]
Are we looking at the "dark side" of Venus? I'd assume the entire gas ball of a cloud system never really gets dark :P

**Comment by fiteclub** [comment]
I don't think that you can make this work without violating the prime directive and altering the course of history.

First commit links to https://www.google.com/search?q=recursion
Second commit links to the first commit.

Following the links:  Second commit (current README.md) --> First Commit --> recursion Google Search

The recursion is broken after the first step.  If you follow the link from the Second commit to the First commit, it just takes you to the version before the recursive link existed.  If you could merge the two commits and retain the SHA of the first commit, or predict the SHA of your initial commit, it would work perfectly.  The John Connor solution might work: send your best soldier back in time so that he will become your father.

**Review by Gaitorius — APPROVED** [review]
https://media.giphy.com/media/3JTpczfnK4q1kbYYaJ/giphy.gif

**Review by dmohar — APPROVED** [review]

**Pull request merged**
