### PR TITLE
Karate and friendship for everyone

### PR DESCRIPTION
**Pull request by fiteclub**
## If this PR were a GIF, what would it be?
teamwork

## Description of change(s)
Add a file We_Are_Go.md for new contributors to test their ability to commit, push, pull request, etc.
Add link to this file in README.md 

## Diligence checklist (omit non-applicable items):
- [x] IDK
- [x] Google gifs for a half hour
- [x] Realize gif link is not working
- [x] @%!@ we'll do it live!!!

### CODE REVIEW

**Comment by fiteclub** [comment]
THE GIFS ARE NOT WORKING!!! EVERYONE PANIC!!!

panic

**Comment by fiteclub** [comment]
Kay. Gif working.

fine

**Review by mathisto — APPROVED** [review]
I'm Matt Kelly, and I approve this message.

**Review by mathisto — APPROVED** [review]
HAWT STUFF 🔥

**Review by dmohar — APPROVED** [review]

**Pull request merged**
